### PR TITLE
Upgrade to Terraform 0.12

### LINKED ISSUE #422: [Terraform v0.12.0-alpha2] Failed to instantiate provider "ibm" to obtain schema...
### Terraform Version

`Terraform v0.12.0-alpha2`

I get this error when using the new *alpha* release of Terraform, v0.12:

```
Error: Failed to instantiate provider "ibm" to obtain schema: Incompatible API version with plugin. Plugin ver
sion: 4, Client versions: [5]
```

### Steps to Reproduce
1. Download [Terraform v0.12](https://releases.hashicorp.com/terraform/0.12.0-alpha2/)
2. `terraform plan` of a workspace making use of this provider

### References
According to [Terraform docs](https://www.terraform.io/upgrade-guides/0-12.html#upgrading-terraform-providers) a new version of the plugin SDK would provide a compatibility layer for the new protocol.

I'll attempt a build against a more recent version of this SDK and report back with a PR hopefully!

### PR DESCRIPTION
**Pull request by giorgioazzinnaro**
Fixes #422 

I've upgraded all the dependencies coming from `hashicorp` and that's it.
The new plugin SDK takes care of the compatibility with the new version of Terraform.

I think I need some guidance for proper testing, maybe you have an environment in IBM Cloud specifically for this?

### CODE REVIEW

**Comment by jjasghar** [comment]
I'm not comfortable putting an alpha `alpha2` release in this. We should wait for the full release in my opinion.

**Comment by giorgioazzinnaro** [comment]
Agreed, I just based my work on master because I wasn't sure about your workflow. But what if was released as an alpha version for the provider as well? After all terraform 0.12 should reach beta in a matter of days and brings some pretty major changes.

**Comment by jjasghar** [comment]
@davetropeano can you chime in here? :metal:

**Comment by giorgioazzinnaro** [comment]
Well, then I'd say, let's just keep this PR alive until 0.12 reaches GA and then we can further bump the SDK version to `0.12.0`

**Comment by sputnik62** [comment]
Not supporting Alpha makes sense but it would be very good to have support for the beta for those of us who want to start the work ahead of the GA.

**Comment by stevestrutt** [comment]
I would be wary of the effort moving to 0.12, even when its beta. The unanswered question in the Terraform forums is how much provider code breaks and how much dev resource is required to fix it. Interested users can always fork the existing provider, upgrade it and run the provider acceptance tests to understand the level of breakage. The IBM instructions for testing start here: https://github.com/IBM-Cloud/terraform-provider-ibm . Terraforms explanation is here:  https://www.terraform.io/docs/extend/testing/acceptance-tests/index.html  . This would be valuable information, without distracting dev from enhancing the existing provider.

**Comment by stevestrutt** [comment]
The way Hashicorp have designed the test suite for a provider is that all tests run automatically. Linked into Travis any push would trigger the whole lot, which will run for hours and cost a fortune as any public push would trigger it! That is unless they are triggered manually. The real question is one of prioritisation of dev time and the level of resource committed to enhancing the provider. Today it is focused on new function and the existing code base.

**Comment by stevestrutt** [comment]
The upside is that this is an open source community and if people have a need to meet their use cases they are free to develop and contribute it themselves. Hashicorp have not made it easy using golang and the development guidance is limited. But there are lots of examples out there. I have a requirement for Cloud Internet Services DNS and global load balancers. I issued the PR yesterday for thousands of lines of code and several new resources, including writing the gloang SDK for the CIS API. It should be available in the next drop of the provider. There are lots of examples on the Internet and I plan to write up how to develop new resources for the IBM provider which should help others down the same path. Terraform 0.12 should be easier for the community to work with as its not writing new code. Fork the provider, govendor in the new Terraform libraries, recompile and run the test suites, find and fix what breaks.

**Comment by giorgioazzinnaro** [comment]
Now that Terraform 0.12 is in beta I think this is relevant again
https://www.terraform.io/upgrade-guides/0-12.html#third-party-providers

**Comment by altvnk** [comment]
Since Terraform 0.12 is already GA, is there any plans to push this forward?

**Comment by stevestrutt** [comment]
@davetropeano can you provide an official response. 
Unofficially the current priority with the provider is to expand the breadth of the current 0.11.x provider starting with VPC support to cover more IBM Cloud functionality. The work to support 0.12 has not been scoped and my investigation so far suggests there maybe a lot of rework due to the HCL changes. The provider dev team is growing and the plan is to get to 0.12 when we can. In practice Hashicorp are likely to need a number of 0.12 revisions before it is stable for practical production usage.

**Comment by davetropeano** [comment]
To Steve's point we haven't scoped the PR or the internal work we need to do yet for 0.12.

There are a number of IBM Cloud specific resources such as VPC support that are taking top priority. 

We will support v0.12 and will publish a timeline. As mentioned, our history with 0.10 and other major releases gives us pause. We feel it is more prudent to wait for the first patch dot release while starting to evaluate the GA -- which was just public 7 days ago.

**Comment by delps1001** [comment]
@davetropeano is there any place I can find a road map about when terraform 0.12.x will be supported?

**Comment by davetropeano** [comment]
Right now this is scheduled for 1q2020. 

https://github.com/IBM-Cloud/terraform-provider-ibm/issues/886

The public roadmap is in a GH project you can track here

https://github.com/IBM-Cloud/terraform-provider-ibm/projects/1

**Comment by hkantare** [comment]
closing this PR request ...As we already migrated to terraform v0.12 support

**Pull request closed without merging**
