### PR TITLE
Terraform v0.12

### PR DESCRIPTION
**Pull request by BlastillROID**
Updated the ansible dynamic inventory sample to support terraform v0.12 tfstate file format

### CODE REVIEW

**Comment by hkantare** [comment]
Terraform v0.12 is not active branch...master is the branch which supports for terraform v0.12.x

**Comment by BlastillROID** [comment]
The problem is that the ansible_dyn_inv in master still supports on the v0.11, should I go ahead and chnag it there?

**Comment by hkantare** [comment]
yes you can gohead and raise the PR for master  branch

**Comment by hkantare** [comment]
closing this pull request we already had a new PR merged
https://github.com/IBM-Cloud/terraform-provider-ibm/commit/3923ce0f812ef96056775d9b6d121d2549b69e11

**Pull request closed without merging**
