### PR TITLE
Security Groups Support for Virtual Endpoint Gatewys

### PR DESCRIPTION
**Pull request by SunithaGudisagarIBM**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by powellquiring** [comment]
Got this:  Suggest: prepare an accelerated rollout. The development (scoped) API spec is available internally for them to work with.

https://ibm-cloudplatform.slack.com/archives/CJG6YPZV2/p1639753867090700?thread_ts=1639740980.086200&cid=CJG6YPZV2



Announcement -- VPE integration with security groupsType: AnnouncementComponent: Virtual Private CloudRegions: Frankfurt, Washington DC, Tokyo, eu-fr2, Dallas, Sao Paulo, Sydney, London, Osaka, TorontoStart Time: 17 Dec 2021, 4:04 AM UTCUpdate Time: 17 Dec 2021, 4:17 AM UTCView affected resources (in subscribed accounts):1870805 - Powell Quiring's Account (713c783d9a507a53135fe6793c37cc74)Region: All  Start Date: 01/12/2022 Event Type: Announcement Severity: Medium  What are we changing? Starting Jan 12, 2022, a new feature will be enabled in the Virtual Private Cloud (VPC) service where new endpoint gateways will require at least one security group. If you omit specifying a security group during endpoint gateway creation, the default security group for the VPC will be used for the endpoint gateway. Existing endpoint gateways are not affected. You can apply a security group to existing gateways at your discretion. After a security group is applied to an existing gateway, it must always have a security group.  Why are we making this change? All IBM Cloud resources aim to be secure by default. By requiring that new endpoint gateways have at least one security group, we are requiring that all traffic flowing through those endpoint gateways be subject to the specific security policies that you control. How will it impact the customer? If you omit specifying a security group during endpoint gateway creation, the default security group for the VPC will be used for the endpoint gateway.  For endpoint gateways created before this feature is released, no security groups are used. You will be able to add security groups to these endpoint gateways, but after doing so, the endpoint gateways can no longer be reverted to use no security groups. Depending on the security group rules, access to IBM services mapped to endpoint gateways may be denied. What actions can you take to avoid a disruption? If you plan to use default security groups for new endpoint gateways, review your default security group rules. If necessary, edit the rules to accommodate your endpoint gateway traffic.

image

**Comment by powellquiring** [comment]
See https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3453

**Comment by astha-jain** [comment]
This branch is old and incomplete. There is PR in our forked repo under review and pending API release. Closing this wrt https://github.com/ibm-vpc/terraform-provider-ibm/pull/61/files

**Comment by SunithaGudisagarIBM** [comment]
there in another PR in forked repo which is in reviewing status

**Pull request closed without merging**
