### PR TITLE
[Fix] enable commit while creating template/version

### PR DESCRIPTION
**Pull request by hariarla**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```
Screenshot 2024-11-18 at 4 27 30 PM
Screenshot 2024-11-18 at 4 28 16 PM

### CODE REVIEW

**Review by alphachart — CHANGES_REQUESTED** [review]
.

**Review by hkantare — APPROVED** [review]

**Review by alphachart — COMMENTED** [review]
.

**Review by alphachart — COMMENTED** [review]
.

**Review by alphachart — COMMENTED** [review]
-

**Pull request merged**
