### PR TITLE
New status by IBM

### PR DESCRIPTION
**Pull request by JoniSanchez**
Solved problem calling to IBM API REST

### CODE REVIEW

**Comment by mrcavern** [comment]
Tested in local and it works.

**Comment by mrcavern** [comment]
@hkantare can we get a patch release for this version?? 

We need to run our pipelines with this change. 

Sorry for duplicating comments, but I don't know where I should have written in first place.

**Comment by hkantare** [comment]
@mrcavern We are planning for minor release tomorrow with some other issues are you OK with date?

**Comment by JoniSanchez** [comment]
@hkantare Yes! No problem, we can wait until tomorrow with the other improvements. Thank you. Anything we can do to help out around here will be welcome.

**Pull request merged**
