### PR TITLE
Add Watson query example

### PR DESCRIPTION
**Pull request by zhdawei**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by kavya498** [comment]
Can you please include it in [documentation](https://registry.terraform.io/providers/IBM-Cloud/ibm/1.37.0/docs/resources/resource_instance) as well as one of the example

Thanks

**Comment by zhdawei** [comment]
@kavya498 how can I update that doc, can you provide a guide?

**Comment by kavya498** [comment]
you ll have to update in the website docs under same repo..
Please add [here](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/website/docs/r/resource_instance.html.markdown#timeouts)

**Comment by zhdawei** [comment]
@kavya498 added doc

**Pull request merged**
