### PR TITLE
Feature: Private DNS support for load balancers

### PR DESCRIPTION
**Pull request by deepaksibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by deepaksibm** [comment]
```

tfpt TestAccIBMISLBDatasource_pDNS
=== RUN   TestAccIBMISLBDatasource_pDNS
--- PASS: TestAccIBMISLBDatasource_pDNS (556.45s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     557.427s

tfpt TestAccIBMISLB_DNS
=== RUN   TestAccIBMISLB_DNS
--- PASS: TestAccIBMISLB_DNS (775.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     776.617s
```

**Comment by deepaksibm** [comment]
```
$ tfpt TestAccIBMISLB_basic_udp

=== RUN   TestAccIBMISLB_basic_udp
--- PASS: TestAccIBMISLB_basic_udp (843.14s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     844.148s
```

**Comment by hkantare** [comment]
Fix the conflicts

**Comment by deepaksibm** [comment]
> Fix the conflicts

resolved conflicts

**Pull request merged**
