### PR TITLE
Database  support for Cassandra added.

### LINKED ISSUE #2590: Database support for Cassandra
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support to the `ibm_database` for the cassandra database: https://cloud.ibm.com/catalog/content/cassandra

### New or Affected Resource(s)

* ibm/resource_ibm_database.go

### Potential Terraform Configuration

```hcl
resource "ibm_database" "test_cassandra" {
  name = "test-cassandra"
  location = "us-south"
  service = "databases-for-cassandra"
  plan = "enterprise"
}
```

### References

Requires updating the bluemix golang SDK: https://github.com/IBM-Cloud/bluemix-go/pull/298

### PR DESCRIPTION
**Pull request by wderezin**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2590 
Relates: bluemix-go https://github.com/IBM-Cloud/bluemix-go/pull/298

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccIBMDatabaseInstance_Cassandra_Basic -run=TestAccIBMDatabaseInstance_Cassandra_Node'

...
```

### CODE REVIEW

**Comment by wderezin** [comment]
This PR will fail until the bluemix PR (https://github.com/IBM-Cloud/bluemix-go/pull/298) is merged.

**Comment by wderezin** [comment]
Acceptance test failing at least in part if not totally due to Token expiration issue:  https://github.ibm.com/compose/compose/issues/22134

**Comment by wderezin** [comment]
Acceptance Test Cases Passed for Cassandra.  Note that PR https://github.com/IBM-Cloud/bluemix-go/pull/302 due to the generally longer provisioning times for Cassandra. 

```
=== RUN   TestAccIBMDatabaseInstance_Cassandra_Basic
=== PAUSE TestAccIBMDatabaseInstance_Cassandra_Basic
=== RUN   TestAccIBMDatabaseInstance_Cassandra_Node
=== PAUSE TestAccIBMDatabaseInstance_Cassandra_Node
=== CONT  TestAccIBMDatabaseInstance_Cassandra_Basic
=== CONT  TestAccIBMDatabaseInstance_Cassandra_Node
--- PASS: TestAccIBMDatabaseInstance_Cassandra_Basic (4251.33s)
--- PASS: TestAccIBMDatabaseInstance_Cassandra_Node (4352.98s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 4354.263s
testing: warning: no tests to run
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/internal/hashcode       (cached) [no tests to run]
```

**Comment by hkantare** [comment]
The bluemix-go PR is merged can you please rebase and fix the detect secrets

**Comment by hkantare** [comment]
closing this PR we released the support as part of Enterprises database support in latest terraform releases

**Pull request closed without merging**
