### PR TITLE
Deprecate key policies from Key Resource

### PR DESCRIPTION
**Pull request by harshit777**

### CODE REVIEW

**Comment by harshit777** [comment]
Tested the code with respect to provisioning with old binary and new binary, no diff can be seen.

**Comment by harshit777** [comment]
https://github.com/IBM-Cloud/terraform-provider-ibm/pull/3047 : we can close this PR since its very old and there has been code restructuring to so path to this PR is not available.

**Review by dinesh-venkatraman-g — APPROVED** [review]
lgtm

**Review by dinesh-venkatraman-g — CHANGES_REQUESTED** [review]
@harshit777 can you add test evidences?

**Comment by harshit777** [comment]
**Old Binary** 
Screenshot 2022-03-21 at 11 14 56 AM
Screenshot 2022-03-21 at 11 12 02 AM

**Terraform plan with New Binary**

Screenshot 2022-03-21 at 11 58 26 AM
Screenshot 2022-03-21 at 12 00 29 PM

**Review by dinesh-venkatraman-g — APPROVED** [review]

**Pull request merged**
