### PR TITLE
fixing private cluster alb hanging

### PR DESCRIPTION
**Pull request by n-marton**
fixing issue: https://github.com/IBM-Cloud/terraform-provider-ibm/issues/484

### CODE REVIEW

**Comment by n-marton** [comment]
that suggestion won't work in a scenario like this:

```hcl
resource "ibm_container_cluster" "cluster" {
  name            = "testing"
  datacenter      = "par01"
  disk_encryption = true
  machine_type    = "u2c.2x4"
  hardware        = "shared"
  no_subnet = false
  private_vlan_id = "2"
  public_vlan_id = "1"

  default_pool_size = "1"
}
```

If I don't specify neither of the vlans, it must be a free cluster which doesn't have ingress as far as I know.
If I only specify a private vlan, than it have to be a private cluster, which doesn't enable ingress by default, so no ingress domain and ingress secret.
If I specify only a public vlan than it will have an ingress and should wait for it's completion, that goes for the scenario if I specify both like in the example above.

**Comment by Praveengostu** [comment]
If you take a look at documentation here https://console.bluemix.net/docs/containers/cs_cli_reference.html#cs_cli_reference it clearly mentions the private and public vlans are optional and created for the first standard cluster. So we need to handle this case as well

**Comment by n-marton** [comment]
```hcl
resource "ibm_container_cluster" "cluster" {
  name            = "testing"
  datacenter      = "par01"
  disk_encryption = true
  machine_type    = "u2c.2x4"
  hardware        = "shared"

  default_pool_size = "1"
}
```

try to run this

**Comment by n-marton** [comment]
there is some difference between the cli tool's and terraform's behaviour because this tf above doesn't work

anyway if anytime the terraform will work same as the cli in this regard, then it should handle the case you pointed out, I think something like this should do the trick

```go
if (noSubnet == false && publicVlanID != "") ||  (noSubnet == false &&  publicVlanID == "" && privateVlanID == ""){
		publicSubnetAdded = true			
	}		
```

**Comment by Praveengostu** [comment]
@n-marton Sorry for the delayed response.. As mentioned in the doc, just passing the private vlan_id does it restrict creating the public vlan_id for the first standard cluster.. I was thinking if we can fix this by coming up with a `private_only` flag similar to cli.

**Pull request merged**
