### PR TITLE
Deprecate old secrets-manager datasources

### PR DESCRIPTION
**Pull request by idohubara**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by hkantare** [comment]
Can you add the deprecation message even in the datasource also so user gets notified as warning

**Comment by idohubara** [comment]
@hkantare done

**Comment by hkantare** [comment]
@idohubara 
Can you please fix the travis issue

**Comment by hkantare** [comment]
Screenshot 2023-04-18 at 11 59 04 AM
https://app.travis-ci.com/github/IBM-Cloud/terraform-provider-ibm/builds/262319242

**Pull request closed without merging**
