### PR TITLE
fix: schematics regional endpoints issue

### PR DESCRIPTION
**Pull request by kavya498**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes https://github.ibm.com/blueprint/product/issues/7432

### CODE REVIEW

**Comment by JonWoodlief** [comment]
Will this allow me to view eu-de workspaces from us-south, and vice versa?

**Comment by JonWoodlief** [comment]
Can you make it configurable as an input on the workspace and workspace outputs datasource?

**Comment by kavya498** [comment]
@JonWoodlief ,
It would not be the right way to do it, as schematics is a regional endpoint..
Client gets initialised only once at provider level..

If you want to do so, you ll have to use provider aliases..

**Comment by JonWoodlief** [comment]
Since we can't predict which region the user will install their workspace into, this means that every single instance of a workspace datasource needs an accompanying provider definition with an alias.

With this solution, if I have a template with 2 workspace data sources, I will have authenticate 3 providers. 1 for the code, and 2 for each of the datasources. That's not an acceptable solution. We are building open source solutions and looking to promote them- these kinds of hacks will reflect poorly on IBM.

**Pull request merged**
