### PR TITLE
fix : ibm_dns_custom_resolver locations 

### PR DESCRIPTION
**Pull request by sandeep645**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by sandeep645** [comment]
This PR has fix to this issue https://github.com/IBM-Cloud/terraform-provider-ibm/issues/3746.

main.tf 
```
resource "ibm_dns_custom_resolver" "test" {
  name        = "testCR-TF"
  instance_id = "< id >"
  description = "testdescription-CR"
  enabled = false
  locations {
    subnet_crn  = "< crn >"
    enabled     = false
  }
  locations {
    subnet_crn  = "< crn >"
    enabled     = false
  }
}
```

Test result :
Custom resolver can now be created with two locations on the same subnet.
image

**Comment by hkantare** [comment]
Can you please share the testcase results

**Comment by hkantare** [comment]
Can you please share the testcase results

**Comment by sandeep645** [comment]
Here is the test case results
image

**Pull request merged**
