### PR TITLE
Fix test bucket endpoints

### PR DESCRIPTION
**Pull request by IBM-Deeksha**
- update bucket endpoints display for test cloud account

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by cjschaef** [comment]
I performed further testing with this change, and it wasn't sufficient still. The data_source also needs a similar update in order to provide the proper endpoint for use.

I made a similar change to the data_source, and tested to verify it worked properly.
https://github.com/cjschaef/terraform-provider-ibm/commit/31ae4aaef82f5b03aac48cefefb9bf692760ddbb

**Comment by cjschaef** [comment]
I did some testing with the additional changes you added, and that does resolve the issues we were seeing during TF create.

However, I also did some destroy testing, it it appears one of the other functions (`resourceIBMCOSBucketExists`) in `resource_ibm_cos_bucket.go` is missing the FileFallBack feature, to use an overridden endpoint.
For reference, this is the change I added that appears to allow the destroy logic to find the existing resource and then delete it.
https://github.com/cjschaef/terraform-provider-ibm/commit/59085f2e8e193b48f895efffcc37bbe6dcfcb472

Sorry, I did not realize this was missed in the initial PR's to add the necessary support for COS endpoint override.
Whether that is a separate PR or can be included in this change, I leave up to you.

**Comment by IBM-Deeksha** [comment]
Thanks again @cjschaef for highlighting. I have made the required changes.

**Comment by cjschaef** [comment]
@IBM-Deeksha I fixed the golang errors and retested and this appears to now be sufficient with our needs to override COS endpoints.
https://github.com/cjschaef/terraform-provider-ibm/commit/5238034c465986fd27694ad436c00ad766d29b1f

I can retest if necessary, once you fix the golang errors, but I expect these changes are good now.

**Comment by IBM-Deeksha** [comment]
Done @cjschaef. Thanks forverifying.

**Review by hkantare — APPROVED** [review]

**Pull request merged**
