### PR TITLE
feature: gpu for instance profile datasource

### PR DESCRIPTION
**Pull request by deepaksibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by deepaksibm** [comment]
Do not merge. waiting for some api spec to be merged

**Comment by hkantare** [comment]
Please add test case results and also update all new attributes to docs

**Comment by deepaksibm** [comment]
```
$ make testacc TEST=./ibm  TESTARGS='-run=TestAccIBMISInstanceProfilesDataSource_basic'
=== RUN   TestAccIBMISInstanceProfilesDataSource_basic
--- PASS: TestAccIBMISInstanceProfilesDataSource_basic (35.33s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 37.920s
$ make testacc TEST=./ibm  TESTARGS='-run=TestAccIBMISInstanceProfileDataSource_basic'
=== RUN   TestAccIBMISInstanceProfileDataSource_basic
--- PASS: TestAccIBMISInstanceProfileDataSource_basic (32.39s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm 36.097s
```

**Comment by deepaksibm** [comment]
> Please add test case results and also update all new attributes to docs

Have added test case results and updated doc changes. let me know if a new test case has to be added. i didn't add a new case as it is a minor attribute addition

**Review by kavya498 — APPROVED** [review]

**Pull request merged**
