### PR TITLE
fix: mark resource group name as computed

### LINKED ISSUE #4170: Resource Group name is not computed
In this [code block](https://github.com/IBM-Cloud/terraform-provider-ibm/blob/master/ibm/service/resourcemanager/resource_ibm_resource_group.go#L25-L28) the resource group name is not computed and this leads to problems. Here is the use case:

The module https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure has an input variable called `powervs_resource_group_name`. 
Inside that modules code, a data lookup on this resource group occurs ([here](https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure/blob/main/submodules/power_workspace/main.tf#L10-L12) for example). 
If I try to execute terraform code that creates a new resource group, and passes the name into this module, the data lookup fails, because the resource group name is not computed, and so is returned straight away, allowing the data lookup to proceed on a group that has not yet been created.

Is there a reason why the name is not computed??

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform IBM Provider Version

```
Terraform v1.2.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/null v3.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/hashicorp/tls v4.0.1
+ provider registry.terraform.io/ibm-cloud/ibm v1.45.1
```

### Affected Resource(s)

* ibm_resource_group

### Terraform Configuration Files

```
##############################
terraform {
  required_version = ">=1.1"
  required_providers {
    ibm = {
      source  = "IBM-Cloud/ibm"
      version = "=1.45.1"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "4.0.1"
    }
  }
}

##############################
provider "ibm" {
  region           = "syd"
  zone             = "syd05"
  ibmcloud_api_key = var.ibmcloud_api_key != null ? var.ibmcloud_api_key : null
}

provider "ibm" {
  alias            = "ibm-is"
  region           = "au-syd"
  zone             = "syd05"
  ibmcloud_api_key = var.ibmcloud_api_key != null ? var.ibmcloud_api_key : null
}
##############################
locals {
  powervs_workspace_name = "${var.prefix}-${var.powervs_zone}-${var.powervs_workspace_name}"
  powervs_sshkey_name    = "${var.prefix}-${var.powervs_zone}-${var.powervs_sshkey_name}"
}

resource "tls_private_key" "tls_key" {
  algorithm = "RSA"
  rsa_bits  = 4096
}

resource "ibm_is_ssh_key" "ssh_key" {
  provider   = ibm.ibm-is
  name       = local.powervs_sshkey_name
  public_key = trimspace(tls_private_key.tls_key.public_key_openssh)
}

resource "ibm_resource_group" "resourceGroup" {
  name     = "test"
}

module "power_infrastructure" {
  source = "git::https://github.com/terraform-ibm-modules/terraform-ibm-powervs-infrastructure.git?ref=v5.0.0"

  powervs_zone                = "syd05"
  powervs_resource_group_name = ibm_resource_group.resourceGroup.name
  powervs_workspace_name      = local.powervs_workspace_name
  tags                        = []
  powervs_sshkey_name         = local.powervs_sshkey_name
  ssh_public_key              = ibm_is_ssh_key.ssh_key.public_key
  ssh_private_key             = trimspace(tls_private_key.tls_key.private_key_openssh)
  access_host_or_ip           = var.access_host_or_ip
  powervs_management_network  = var.powervs_management_network
  powervs_backup_network      = var.powervs_backup_network
  transit_gateway_name        = var.transit_gateway_name
  reuse_cloud_connections     = var.reuse_cloud_connections
  cloud_connection_count      = var.cloud_connection_count
  cloud_connection_speed      = var.cloud_connection_speed
  cloud_connection_gr         = var.cloud_connection_gr
  cloud_connection_metered    = var.cloud_connection_metered
  squid_config                = var.squid_config
  dns_forwarder_config        = var.dns_forwarder_config
  ntp_forwarder_config        = var.ntp_forwarder_config
  nfs_config                  = var.nfs_config
  perform_proxy_client_setup  = var.perform_proxy_client_setup
}
```
### Expected Behavior

The data lookup should not occur on the resource group until it has been created

### Actual Behavior

The data lookup occurs because the resource group name is not computed, and is returned straight away. This means that even terraform plan fails with:

```
module.power_infrastructure.module.power_workspace.data.ibm_resource_group.resource_group_ds: Reading...
╷
│ Error: [ERROR] Given Resource Group is not found in the account : %!s(<nil>) {
│     "StatusCode": 200,
│     "Headers": {
│         "Cache-Control": [
│             "max-age=0, no-cache, no-store"
│         ],
│         "Content-Length": [
│             "16"
│         ],
│         "Content-Type": [
│             "application/json; charset=utf-8"
│         ],
│         "Date": [
│             "Tue, 15 Nov 2022 13:30:45 GMT"
│         ],
│         "Etag": [
│             "W/\"10-snEjXFi4SWmfY0hH7xVHSX5MF4M\""
│         ],
│         "Expires": [
│             "Tue, 15 Nov 2022 13:30:45 GMT"
│         ],
│         "Pragma": [
│             "no-cache"
│         ],
│         "Server": [
│             "istio-envoy"
│         ],
│         "Set-Cookie": [
│             "ak_bmsc=9023656E822830D2F5BCC746AFB82CB5~000000000000000000000000000000~YAAQJtERAkl6EnqEAQAAjyp8exFDPCBuTcSX7kfAnGQGV8qbvTbUNWjuhlnFQcqGH8RrfBEQuRgPrRB+nyNv3AXDjnwiRTLo7Di64ST4ZxOhulSA8QADYdeQQHwjSGAwIfYR1ffh6fPwarDT3i87SMxczz0SxdvlTAMmb5nC9G2TZeILemB9jI6IdMaSZv6cGVvMrWMC7zraJslAMRSEUdrT4aHfuufKQLFmA/DfAVstDRDGyPlJjK/BU0w9OxyHHhegJEI/0zsUSVqlYiLshpTPNEsW8k/SzCLsLIJdL8zDuWf0tYcVKas10pg3MdMPEFNKjbn5jcUxvHNCbVmgfIAevSMwoXF4fzbK3g8asP+o92LOCaFsxV1+Z8DcFxaJvwab51vgz9rn5KLrXg==; Domain=.cloud.ibm.com; Path=/; Expires=Tue, 15 Nov 2022 15:30:45 GMT; Max-Age=7200; HttpOnly"
│         ],
│         "Strict-Transport-Security": [
│             "max-age=31536000; includeSubDomains"
│         ],
│         "Transaction-Id": [
│             "abb5f462af7b42deb9ab3d6577f2f1bb"
│         ],
│         "Vary": [
│             "Accept-Encoding"
│         ],
│         "X-Content-Type-Options": [
│             "nosniff"
│         ],
│         "X-Envoy-Upstream-Service-Time": [
│             "368"
│         ],
│         "X-Ratelimit-Limit": [
│             "60"
│         ],
│         "X-Ratelimit-Remaining": [
│             "59"
│         ],
│         "X-Ratelimit-Reset": [
│             "0"
│         ],
│         "X-Request-Id": [
│             "abb5f462af7b42deb9ab3d6577f2f1bb"
│         ],
│         "X-Response-Time": [
│             "354.619ms"
│         ],
│         "_request_id": [
│             "abb5f462af7b42deb9ab3d6577f2f1bb"
│         ]
│     },
│     "Result": {
│         "resources": []
│     },
│     "RawResult": null
│ }
│ 
│ 
│   with module.power_infrastructure.module.power_workspace.data.ibm_resource_group.resource_group_ds,
│   on .terraform/modules/power_infrastructure/submodules/power_workspace/main.tf line 10, in data "ibm_resource_group" "resource_group_ds":
│   10: data "ibm_resource_group" "resource_group_ds" {
│ 
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by ocofaigh**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #4170

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by hkantare** [comment]
You can't use a computed with Required Type
Screenshot 2022-11-16 at 12 49 00 PM
https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#section-readme

**Comment by ocofaigh** [comment]
@hkantare Do you have any suggestions on how to solve https://github.com/IBM-Cloud/terraform-provider-ibm/issues/4170 then?

**Comment by hkantare** [comment]
@ocofaigh Which module you are using to create the resource group? can't we use the depends_on for module to wait for resource group creation

**Comment by ocofaigh** [comment]
@hkantare yes the workaround is to use `depends_on`. However this is only supposed to be used as a last resort. I think what I am going to do is suggest that the owners of the `terraform-ibm-powervs-infrastructure` module actually change their input to require resource group ID instead of name and that would mean they could remove those data lookups that cause the issue here, and also no depends_on would be required anymore.

**Pull request closed without merging**
