### PR TITLE
support for vpc dns resolution binding

### PR DESCRIPTION
**Pull request by ujjwal-ibm**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
=== RUN   TestAccIBMISVirtualEndpointGateway_AllowDnsResolutionBinding
--- PASS: TestAccIBMISVirtualEndpointGateway_AllowDnsResolutionBinding (127.11s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     129.230s
```

```
=== RUN   TestAccIBMISVirtualEndpointGatewayDataSource_AllowDnsResolutionBinding
--- PASS: TestAccIBMISVirtualEndpointGatewayDataSource_AllowDnsResolutionBinding (110.66s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     112.854s
```

```
=== RUN   TestAccIBMISVirtualEndpointGatewaysDataSource_AllowDnsResolutionBinding
--- PASS: TestAccIBMISVirtualEndpointGatewaysDataSource_AllowDnsResolutionBinding (104.28s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     106.417s
```

```
=== RUN   TestAccIBMIsVPCDnsResolutionBindingResourceBasic
--- PASS: TestAccIBMIsVPCDnsResolutionBindingResourceBasic (72.63s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     74.793s
```

```
=== RUN   TestAccIBMIsVPCDnsResolutionBindingsDataSourceBasic
--- PASS: TestAccIBMIsVPCDnsResolutionBindingsDataSourceBasic (69.61s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     71.873s
```

```
=== RUN   TestAccIBMIsVPCDnsResolutionBindingDataSourceBasic
--- PASS: TestAccIBMIsVPCDnsResolutionBindingDataSourceBasic (73.08s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     75.238s
```

```
=== RUN   TestAccIBMISVPC_dns_system
--- PASS: TestAccIBMISVPC_dns_system (107.33s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     109.737s
```

```
=== RUN   TestAccIBMISVPC_dns_manual
--- PASS: TestAccIBMISVPC_dns_manual (120.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     122.357s
```

```
=== RUN   TestAccIBMISVPC_dns_manual2
--- PASS: TestAccIBMISVPC_dns_manual2 (138.51s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     142.436s
```

```
=== RUN   TestAccIBMISVPC_dns_delegated
--- PASS: TestAccIBMISVPC_dns_delegated (390.50s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     392.699s
```

### CODE REVIEW

**Comment by kavya498** [comment]
Travis failed please resolve.
and also please attach existing vpc testcases as you made changes to that resource and datasource.
thanks.

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISVPCDatasource_basic
--- PASS: TestAccIBMISVPCDatasource_basic (89.41s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     91.574s
```

```
=== RUN   TestAccIBMISVPCsDatasource_basic
--- PASS: TestAccIBMISVPCsDatasource_basic (239.09s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     241.379s
```

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISVPC_basic
--- PASS: TestAccIBMISVPC_basic (168.67s)
=== RUN   TestAccIBMISVPC_basic_apm
--- PASS: TestAccIBMISVPC_basic_apm (133.76s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     304.286s
```

**Review by kavya498 — APPROVED** [review]

**Comment by ujjwal-ibm** [comment]
```
=== RUN   TestAccIBMISVPC_securityGroups
--- PASS: TestAccIBMISVPC_securityGroups (85.26s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     87.152s
```

```
=== RUN   TestAccIBMISVPC_noSGACLRules
--- PASS: TestAccIBMISVPC_noSGACLRules (74.32s)
PASS
ok      github.com/IBM-Cloud/terraform-provider-ibm/ibm/service/vpc     76.207s
```

**Pull request merged**
