### PR TITLE
Update UKO plugin to use the UKO 4.7 version of the sdk

### PR DESCRIPTION
**Pull request by justin-patzer**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by kavya498** [comment]
@justin-patzer ,
Can you please share testcase results?

**Comment by justin-patzer** [comment]
We don't currently have automated tests for this. I believe they're being worked on, but they aren't ready at this point. The plugin was tested manually.

I'll get the docs updated as quickly as possible.

**Comment by justin-patzer** [comment]
Docs have been updated.

**Comment by justin-patzer** [comment]
Testing involved using a tf file provided by our test team with a vault, every type of keystore and key template, and 2 copies of each managed key. We did the following:
1. Created all these resources, verified through the web UI that they came up successfully
2. Edited the descriptions of each to prompt an update, verified that went through.
3. Edited the state of each key to move them to deactivated, and then destroyed, verifying that each succeeded
4. Destroyed all the resources, and verified they were removed.

**Comment by justin-patzer** [comment]
Successful Apply
Screenshot 2023-03-17 at 1 52 13 PM
image (5)
image (6)
image (7)

**Comment by justin-patzer** [comment]
Successful Destroy:
Screenshot 2023-03-17 at 2 05 25 PM
image (8)
image (9)
No Keystores to show, since they're shown in vault, which is deleted

**Comment by kavya498** [comment]
@justin-patzer ,
Documentation is not inline with the schema.

Kindly add all attributes of resources / datasources to its respective docs.
If there is a forcenew on argument please document it accordingly in respective doc file.

Thanks

**Comment by justin-patzer** [comment]
I've updated the docs to match the schemas.

**Review by kavya498 — APPROVED** [review]

**Pull request merged**
