### PR TITLE
Clevos 94481 remove hardcoded endpoints

### PR DESCRIPTION
**Pull request by IBM-Deeksha**
Contributes to: https://jiracloud.swg.usma.ibm.com:8443/browse/CLEVOS-94481

- remove hardcoded values for private and direct cos config endpoint. Use defaults values when no env variables are set

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by cjschaef** [comment]
I was doing some testing using this branch, I hit some errors. Will try to get more details to see if it is a configuration issue or a bug.

**Comment by IBM-Deeksha** [comment]
Thanks @cjschaef . If possible could you please share the error message that you're getting

**Comment by cjschaef** [comment]
This is the error I receive
```
time="2024-07-16T01:45:57Z" level=error msg="Error: [ERROR] Error retrieving service offering: Request failed with status code: 404, ServerErrorResponse: {\"message\":\"Requested page not found.\",\"code\":404,\"global_transaction_id\":\"7c7b2f09-ec3c-408e-a60b-23f5efbbd618\"}"
time="2024-07-16T01:45:57Z" level=error
time="2024-07-16T01:45:57Z" level=error
time="2024-07-16T01:45:57Z" level=error msg="  with ibm_resource_instance.cos,"
time="2024-07-16T01:45:57Z" level=error msg="  on main.tf line 28, in resource \"ibm_resource_instance\" \"cos\":"
time="2024-07-16T01:45:57Z" level=error msg="  28: resource \"ibm_resource_instance\" \"cos\" {"
time="2024-07-16T01:45:57Z" level=error
time="2024-07-16T01:45:57Z" level=error msg=---
time="2024-07-16T01:45:57Z" level=error msg="id: terraform-446cc00a"
time="2024-07-16T01:45:57Z" level=error msg="summary: |"
time="2024-07-16T01:45:57Z" level=error msg="  [ERROR] Error retrieving service offering: Request failed with status code: 404, ServerErrorResponse: {\"message\":\"Requested page not found.\",\"code\":404,\"global_transaction_id\":\"7c7b2f09-ec3c-408e-a60b-23f5efbbd618\"}"
time="2024-07-16T01:45:57Z" level=error msg="severity: error"
time="2024-07-16T01:45:57Z" level=error msg="resource: ibm_resource_instance"
time="2024-07-16T01:45:57Z" level=error msg="operation: create"
time="2024-07-16T01:45:57Z" level=error msg="component:"
time="2024-07-16T01:45:57Z" level=error msg="  name: github.com/IBM-Cloud/terraform-provider-ibm"
time="2024-07-16T01:45:57Z" level=error msg="  version: 1.65.0"
time="2024-07-16T01:45:57Z" level=error msg=---
```

With this definition
```
resource "ibm_resource_instance" "cos" {
  name              = "${var.cluster_id}-cos"
  service           = "cloud-object-storage"
  plan              = "standard"
  location          = "global"
  resource_group_id = local.resource_group_id
  tags              = local.tags
}
```

**Comment by cjschaef** [comment]
From what I understand, I don't see how this relates to your changes, so I am continuing to get more details.

**Comment by cjschaef** [comment]
I think I have identified the issue is related to Global Catalog endpoint, not your changes. I will continue to try to test to confirm things.

**Review by hkantare — APPROVED** [review]

**Pull request merged**
